### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by UncleEnk** [excalith/excalith-start-page#2] opened 2023-02-11 19:49 UTC
I have been trying to debug this for a while (like 3 days), and I have had a consistent failure with commands. I'm not sure what the problem is, but I believe it is the regex. I would appreciate if i got some help

**Comment by UncleEnk** [comment] 2023-02-11 19:50
whoops misclicked

**Comment by excalith** [comment] 2023-02-11 20:55
Sorry, afk at the moment. Will look into that later. However, can you please provide more details? An example query you type, browser log for possible errors etc anything you can provide. Otherwise it would be really hare to try to find a way to reproduce something.

**Comment by UncleEnk** [comment] 2023-02-12 02:14
I will try to find logs of some sort, but I cannot figure it out. Though it shouldn't be very difficult to recreate it because it happens every time I try to use a command (unless help or nfetch)

**Comment by UncleEnk** [comment] 2023-02-12 02:14
I can send video of whats happening if that would help

**Comment by UncleEnk** [comment] 2023-02-12 02:15
If it helps, what's happening is it's searching the command up instead of "running"(?) it

**Comment by excalith** [comment] 2023-02-12 07:52
Hello, as I mentioned above I need all the data you can provide.

- What do you write to run commands? Please **type exactly what you write** there
- Launch start page, open browser console, reload the page and send me a screenshot of the console https://firefox-source-docs.mozilla.org/devtools-user/browser_console/index.html this will show all errors

It is not possible to reproduce with what you have shared so far, and no one ever encountered this issue before. So, I need more information to help you.

And just a friendly warning in case you might not now, please do not use github issues for multiple consecutive messages like as messaging services such as whatsapp. Github will send notifications to each following people for your each message and it gets annoying to receive them while at work / free. Instead, prepare your draft and send it when you complete.

**Comment by excalith** [comment] 2023-02-17 12:27
Hello @UncleEnk any updates regarding your issue? I cannot reproduce what you have there, so if I can't hear from you I will close this issue with `cant reproduce` flag.

**Comment by excalith** [comment] 2023-02-18 12:16
Since no one else reported such an issue and I haven't received more information from you, I am closing this issue as `cant reproduce`.

**Closed by excalith** 2023-02-18 12:16 UTC
Labels: cant-reproduce

**Comment by UncleEnk** [comment] 2023-02-26 18:15
Sorry for not responding. I have been very busy. 
Here is the log without me attempting to do any commands
![the image without running a command](https://i.imgur.com/sllJUzr.png) 

And the log with me attempting to do the commands is this (very similar)
![the image when I ran a command](https://i.imgur.com/TtIhOOV.png)

From looking at the logs, it looks like it is related to "WebExtension context". Since I am not very proficient in web dev, I do not understand what this means! Sorry for being so late to respond. I hope I can help later on. Bye.

**Comment by excalith** [comment] 2023-02-26 21:52
This sounds like an issue with your browser. Can you please try 
launching the link in private mode without any extensions installed? If you cannot do that, try with a different browser? Also, I would love to see one of the WebContext errors more. You can click the little arrow on the left side of the error to expand it further. Also your browser and OS version should help identifying the problem. But as I said, it doesn't look like an issue with the code.

**Comment by UncleEnk** [comment] 2023-02-26 23:33
Wow, it seems to me that Firefox dev tools has refused to work consistently. Now I am getting this log:
![errors are weirdly inconsistent](https://i.imgur.com/azAV35P.png) 
(I have shown the "tree" of the WebExtension Context error)
This is how it looks in private mode with no extensions enabled:
![idk the issue](https://i.imgur.com/Yr8fc6R.png)

**Comment by UncleEnk** [comment] 2023-02-26 23:37
Sorry for leaving two messages, I forgot to say that, My Firefox version is 110.0 (64 bit) and that my windows version is "Build 22621.1265"

**Comment by excalith** [comment] 2023-02-27 08:46
Ooops, I realized that you sent logs from `Browser Console`. Can you try the logs from `Menu > More Tools > Web Developer Tools > Console` for the logs? This is the console shows logs for the web app, we might find something useful there instead of `Browser Console` logs

1. Launch excalith-start-page.vercel.app/
2. Open the console logs from the path I mentioned above
3. Reload the page 
4. Check the logs
